# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CLion.app/Contents/bin/cmake/bin/cmake

# The command to remove a file.
RM = /Applications/CLion.app/Contents/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/Users/yimengli/Dropbox/job Hunting/airportsimulator-yimengli"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/Users/yimengli/Dropbox/job Hunting/airportsimulator-yimengli"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CLion.app/Contents/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/Applications/CLion.app/Contents/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/yimengli/Dropbox/job Hunting/airportsimulator-yimengli/CMakeFiles" "/Users/yimengli/Dropbox/job Hunting/airportsimulator-yimengli/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/yimengli/Dropbox/job Hunting/airportsimulator-yimengli/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named AirportSimulator

# Build rule for target.
AirportSimulator: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 AirportSimulator
.PHONY : AirportSimulator

# fast build rule for target.
AirportSimulator/fast:
	$(MAKE) -f CMakeFiles/AirportSimulator.dir/build.make CMakeFiles/AirportSimulator.dir/build
.PHONY : AirportSimulator/fast

airport.o: airport.cpp.o

.PHONY : airport.o

# target to build an object file
airport.cpp.o:
	$(MAKE) -f CMakeFiles/AirportSimulator.dir/build.make CMakeFiles/AirportSimulator.dir/airport.cpp.o
.PHONY : airport.cpp.o

airport.i: airport.cpp.i

.PHONY : airport.i

# target to preprocess a source file
airport.cpp.i:
	$(MAKE) -f CMakeFiles/AirportSimulator.dir/build.make CMakeFiles/AirportSimulator.dir/airport.cpp.i
.PHONY : airport.cpp.i

airport.s: airport.cpp.s

.PHONY : airport.s

# target to generate assembly for a file
airport.cpp.s:
	$(MAKE) -f CMakeFiles/AirportSimulator.dir/build.make CMakeFiles/AirportSimulator.dir/airport.cpp.s
.PHONY : airport.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/AirportSimulator.dir/build.make CMakeFiles/AirportSimulator.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/AirportSimulator.dir/build.make CMakeFiles/AirportSimulator.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/AirportSimulator.dir/build.make CMakeFiles/AirportSimulator.dir/main.cpp.s
.PHONY : main.cpp.s

parking_stand.o: parking_stand.cpp.o

.PHONY : parking_stand.o

# target to build an object file
parking_stand.cpp.o:
	$(MAKE) -f CMakeFiles/AirportSimulator.dir/build.make CMakeFiles/AirportSimulator.dir/parking_stand.cpp.o
.PHONY : parking_stand.cpp.o

parking_stand.i: parking_stand.cpp.i

.PHONY : parking_stand.i

# target to preprocess a source file
parking_stand.cpp.i:
	$(MAKE) -f CMakeFiles/AirportSimulator.dir/build.make CMakeFiles/AirportSimulator.dir/parking_stand.cpp.i
.PHONY : parking_stand.cpp.i

parking_stand.s: parking_stand.cpp.s

.PHONY : parking_stand.s

# target to generate assembly for a file
parking_stand.cpp.s:
	$(MAKE) -f CMakeFiles/AirportSimulator.dir/build.make CMakeFiles/AirportSimulator.dir/parking_stand.cpp.s
.PHONY : parking_stand.cpp.s

runway.o: runway.cpp.o

.PHONY : runway.o

# target to build an object file
runway.cpp.o:
	$(MAKE) -f CMakeFiles/AirportSimulator.dir/build.make CMakeFiles/AirportSimulator.dir/runway.cpp.o
.PHONY : runway.cpp.o

runway.i: runway.cpp.i

.PHONY : runway.i

# target to preprocess a source file
runway.cpp.i:
	$(MAKE) -f CMakeFiles/AirportSimulator.dir/build.make CMakeFiles/AirportSimulator.dir/runway.cpp.i
.PHONY : runway.cpp.i

runway.s: runway.cpp.s

.PHONY : runway.s

# target to generate assembly for a file
runway.cpp.s:
	$(MAKE) -f CMakeFiles/AirportSimulator.dir/build.make CMakeFiles/AirportSimulator.dir/runway.cpp.s
.PHONY : runway.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... AirportSimulator"
	@echo "... airport.o"
	@echo "... airport.i"
	@echo "... airport.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... parking_stand.o"
	@echo "... parking_stand.i"
	@echo "... parking_stand.s"
	@echo "... runway.o"
	@echo "... runway.i"
	@echo "... runway.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

